// Static image imports (`import img from "…/player.png"`, audit L24) are typed
// by Next's own declarations. next-env.d.ts references them too, but it is
// generated by `next dev`/`next build` and git-ignored, and CI runs
// `tsc --noEmit` before the build, so the reference lives here as well.
/// <reference types="next/image-types/global" />
